#!/bin/bash

# Check coding style only on merge requests
if [ -z "${CI_MERGE_REQUEST_IID}" ]; then
  exit 0
fi

# We Cannot use git-clang-format here because we have a shallow clone.
# It's faster to download the diff than unshallowing.
DIFF_FILE=${CI_MERGE_REQUEST_IID}.diff
curl -O ${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/$DIFF_FILE || exit $?

# GitLab gives us a plain diff with lines of context that we don't want to
# reformat. This reverse the diff and regenerate it without context.
git apply --reverse $DIFF_FILE
git diff -R -U0 > $DIFF_FILE
git reset --hard HEAD

DIFF=$(cat $DIFF_FILE | clang-format-diff.py -p1 -regex ".*\.(c|cpp)") || exit $?
if [ -n "$DIFF" ]; then
  echo "$DIFF"
  echo "-- code style errors --"
  clang-format --version
  exit 1
fi
