#!/bin/sh

GIT_CLANG_FORMAT=$(command -v git-clang-format)
if [ -z "$GIT_CLANG_FORMAT" ]; then
  echo "WARNING: git-clang-format not found."
  echo "It is recommended to install clang-format or use an IDE that bundles it (e.g. vscode)."
  echo "Coding style check might fail on CI otherwise."
  echo "It is recommended to use latest version:"
  echo "- pip install clang-format"
  exit 0
fi

# Quote $GIT_CLANG_FORMAT because it could contain spaces (e.g. "C:\Program Files\").
"$GIT_CLANG_FORMAT" -f --extensions c,cpp $@
exit $?
