/* GStreamer
 *  Copyright (C) 2024 Centricular Ltd
 *     Author: Jochen Henneberg <jochen@centricular.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the0
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "gstvp8bitwriter.h"
#include <gst/base/gstbitwriter.h>

#define WRITE_BITS_UNCHECK(bw, val, nbits)                                    \
  (nbits <= 8 ? gst_bit_writer_put_bits_uint8 (bw, val, nbits) :              \
   (nbits <= 16 ? gst_bit_writer_put_bits_uint16 (bw, val, nbits) :           \
    (nbits <= 32 ? gst_bit_writer_put_bits_uint32 (bw, val, nbits) :          \
     FALSE)))

#define WRITE_BITS(bw, val, nbits)                                            \
  if (!WRITE_BITS_UNCHECK (bw, val, nbits)) {                                 \
    g_warning ("Unsupported bit size: %u", nbits);                            \
    have_space = FALSE;                                                       \
    goto error;                                                               \
  }

/**
 * gst_vp8_bit_writer_frame_header:
 * @frame_hdr: the frame header of #GstVp8FrameHdr to write
 * @data: (out caller-allocates)(not nullable): the stream
 *  generated by the frame header
 * @size: (inout): the size in bytes of the input and output
 *
 * Generating the according VP8 bit stream by providing the frame header.
 *
 * Returns: a #GstVp8BitWriterResult
 *
 * Since: 1.24
 **/
GstVp8BitWriterResult
gst_vp8_bit_writer_frame_header (const GstVp8FrameHdr * frame_hdr,
    guint8 * data, guint * size)
{
  gboolean have_space = TRUE;
  GstBitWriter bw;

  g_return_val_if_fail (frame_hdr != NULL, GST_VP8_BIT_WRITER_ERROR);
  g_return_val_if_fail (data != NULL, GST_VP8_BIT_WRITER_ERROR);
  g_return_val_if_fail (size != NULL, GST_VP8_BIT_WRITER_ERROR);
  g_return_val_if_fail (*size > 0, GST_VP8_BIT_WRITER_ERROR);

  gst_bit_writer_init_with_data (&bw, data, *size, FALSE);

  /* whether this is a keyframe (0) or not (1) */
  WRITE_BITS (&bw, !frame_hdr->key_frame, 1);
  /* version */
  WRITE_BITS (&bw, frame_hdr->version, 3);
  /* show frame */
  WRITE_BITS (&bw, frame_hdr->show_frame, 1);
  /* show frame */
  WRITE_BITS (&bw, frame_hdr->data_chunk_size, 19);

  if (frame_hdr->key_frame) {
    /* start code */
    WRITE_BITS (&bw, 0x9d, 8);
    WRITE_BITS (&bw, 0x01, 8);
    WRITE_BITS (&bw, 0x2a, 8);
    WRITE_BITS (&bw, (frame_hdr->horiz_scale_code & 0x02) << 14 |
        (frame_hdr->width & 0x3fff), 16);
    WRITE_BITS (&bw, (frame_hdr->vert_scale_code & 0x02) << 14 |
        (frame_hdr->height & 0x3fff), 16);
  }

  g_assert (gst_bit_writer_get_size (&bw) % 8 == 0);
  *size = gst_bit_writer_get_size (&bw) / 8;

  gst_bit_writer_reset (&bw);

  return GST_VP8_BIT_WRITER_OK;

error:
  gst_bit_writer_reset (&bw);
  *size = 0;
  return have_space ? GST_VP8_BIT_WRITER_INVALID_DATA :
      GST_VP8_BIT_WRITER_NO_MORE_SPACE;
}
